### ISSUE TITLE
PubSub with Tcp

### ISSUE THREAD

**Issue by TimoHeiten** [TimoHeiten/zer0mqXt#4]
Pub Sub pattern with tcp

**Comment by TimoHeiten** [comment]
apparently this issue was solved by implementing the pubsub retry policy (which required to change the bind and connect calls from subscriber to publisher and made it work 4 tcp)

![image](https://user-images.githubusercontent.com/20025919/135732365-fe270337-0036-4672-a49d-c8a02002ff7d.png)

**Comment by Flash0ver** [comment]
i.e. issue #6, PR #51
