### ISSUE TITLE
Introduce RetryCount to PubSub retry policy

### ISSUE THREAD

**Issue by Flash0ver** [TimoHeiten/zer0mqXt#52]
In #6, we've introduced a retry policy for the PubSub pattern, which is controlled by a `bool RetryIsActive` and tries one single time again if the first try fails.
We would also like to introduce a `int RetryCount` to control the maximum amount of retries.

We could either add the `RetryCount` next to the boolean flag, which defaults to `1` to keep the current default behavior unchanged.
Or we could replace the flag with the count, also defaulting to `1`, which still keeps the current default behavior unchanged.

**Comment by TimoHeiten** [comment]
Retry for PubSub does not comply with the pattern as described in the [documentation](https://zguide.zeromq.org/docs/chapter1/)

So I still agree with the idea, but only for the ReqRep pattern (or maybe others too, when we have created them)
